language: generic 
services:
  - docker

before_install:
  - docker build -t parselynk/dokcer-react -f Dockerfile.dev .

script:
  - docker run -e CI=true parselynk/dokcer-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-309934827588"
  bucket_path: "docker-react" #equal to app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
